### ISSUE TITLE
File extensions are case sensitive

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/inselect#268]
Perhaps just on Linux, but I'd assume this may be the case on Mac too. Inselect can open .jpg but not .JPG

**Comment by quicklizard99** [comment]
This was fixed, at least for Mac OS, in #159. Just tested on Ubuntu 14.04 and works OK.

@edwbaker could you provide a little more info? Does the File, Open box not allow .JPG files to be selected? Does Inselect raise an error when you open a .JPG file?

**Comment by edwbaker** [comment]
Yes - my mistake - I didn't realise there were releases after 0.1.9 as git lists them alphabetically. 

Inselect does however change the file permissions of the original image, and all thumbnails it generates, to be ready only though. Is this intentional? (This happens on master).

**Comment by quicklizard99** [comment]
Good to know that we don't have a problem with case sensitivity.

@edwbaker - yes, that behaviour was added in order to prevent users from accidentally deleting their data. It is an unexpected side-effect of opening an image in Inselect, though, so maybe this is not sensible.

@llivermore @edwbaker - your thoughts?

**Comment by edwbaker** [comment]
I'd say it was not the job of Inselect to prevent users doing that. It's a tool for segmentation and analysis. I found it unexpected behaviour and assumed it was a bug.

**Comment by quicklizard99** [comment]
Yes, think I agree. Will close this issue and raise one about read-only stuff.
